## 01 Installing R Packages

# Start installing packages from CRAN
# Install packages

```{r}
install.packages("dplyr")
install.packages("BiocManager")
```

#To call the library to our environment

```{r}
library(dplyr)
library(BiocManager)
```


```{r}
sessionInfo()
```

#```{r}
#Now install specific packages from Bioconductor
install("PeacoQC")
```

```{r}
library(PeacoQC)
```
```{r}
sessionInfo()
```

#```{r}
#To avoid error when installing a github packaging
install.packages("remotes")
```

```{r}
library(remotes)
```


# Christopher Hall - Flow Cytometry Data Analysis in R

```{r}
install_github("hally166/flowSpectrum")
```


```{r}
install.packages("tidyverse")
install.packages("purrr")
```

```{r}
library(purrr)
```

```{r}
#To know package version
packageVersion("PeacoQC")
```

```{r}
#Citar algun paquete en publicaciones
citation("PeacoQC")
```


```{r}
#To install a package at a particular version, use the function remotes
#remotes::install_version("ggplot2", version = "3.5.2", repos = "https://cloud.r-project.org")
#For Github based packages
#remotes::install_github("DavidRach/lugiernaga", ref = "v0.99.7")
#Or if no new release, checj the guthub commit number
#remotes::install_github("DavidRach/Luciernaga", ref = "8d1d694")
```

```{r}
install("flowCore")
```

```{r}
#To detect where the packages came from, google the name of the package
#See if you can spot first either a CRAN or a Bioconductor website. Then enter the respective installation command (install.packages(), install(), install_github()) for the appropiate repository, add the package name, and run the code to see if the installation proceeds.
```

```{r}
# Location: CRAN, Website: https://purrr.tidyverse.org/
#enhances working with tools for working with functions and vectors
install.packages("purrr")
```

```{r}
# Location: Bioconductor, https://www.bioconductor.org/packages/release/bioc/html/flowCore.html
#Basic structures for flow cytometry data
install("flowCore")
```

```{r}
#Location: Bioconductor. https://www.bioconductor.org/packages/release/bioc/html/flowWorkspace.html
#This package is designed to facilitate comparison of automated gating methods against manual gating done in flowJo.
install("flowWorkspace")
```

```{r}
#Location: CRAN.Website: https://stringr.tidyverse.org/
install.packages("stringr")
```

```{r}
#Location: CRAN.Website: https://ggplot2.tidyverse.org/
install.packages("ggplot2")
```

```{r}
#Location: BiocManager. Website: https://www.bioconductor.org/packages/release/bioc/html/ggcyto.html
#is a cytometry data visualization tool built around ggplot and the grammar of graphics paradigm.
install.packages("ggcyto")
```

```{r}
#Location: CRAN. Website: https://tidyr.tidyverse.org/
#The goal of tidyr is to help you create tidy data. Tidy data is data where:
# Each variable is a column; each column is a variable.
# Each observation is a row; each row is an observation.
# Each value is a cell; each cell is a single value.

install.packages("tidyr")
```

```{r}
#Location: Bioconductor Website: https://www.bioconductor.org/packages/release/bioc/html/openCyto.html
#This package is designed to facilitate the automated gating methods in sequential way to mimic the manual gating strategy.
install.packages("openCyto")
```

```{r}
#Location: Bioconductor Website: https://www.bioconductor.org/packages/release/bioc/html/FlowSOM.html
# is a tool for the clustering and visualization of high-dimensional cytometry data (flow cytometry and mass cytometry), primarily used in fields like immunology and oncology.
library("FlowSOM")
```

```{r}
#Location: CRAN Website:  https://xml2.r-lib.org/
#provides a simple and consistent interface for working with both XML and HTML data in R
install.packages("xml2")
```

```{r}
# Install devtools from CRAN
install.packages("devtools")
library(devtools)
```
```{r}
# is a normalization tool designed to remove batch effects in cytometry data (flow and mass cytometry) by using control samples run across all batches
#Location: Github Website: https://github.com/saeyslab/CytoNorm
library(devtools)
install_github('saeyslab/CytoNorm')
```

```{r}
#Location: CRAN Website: https://cran.r-project.org/web/packages/lubridate/index.html
install.packages("lubridate")
```

```{r}
#Location: CRAN Website:https://cran.r-project.org/web/packages/httr2/index.html
#https://httr2.r-lib.org/
install.packages("httr2")
```

```{r}
#Location: Bioconductor Website: https://bioconductor.org/packages/devel/bioc/html/flowGate.html
#Using flowGate, you can draw 1D and 2D span/rectangle gates, quadrant gates, and polygon gates on flow cytometry data by interactively drawing the gates on a plot of your data, rather than by specifying gate coordinates. This package is especially geared toward wet-lab cytometerists looking to take advantage of R for cytometry analysis, without necessarily having a lot of R experience.
install.packages("flowGate")
```

```{r}
#Location: CRAN Website:
# a comprehensive collection of tools for the R programming language designed to simplify and expedite the process of developing R packages Website: https://devtools.r-lib.org/
install.packages("devtools")
```

```{r}
# Location: CRAN
# Website: https://plotly.com/r/getting-started/
install.packages("plotly")
```

```{r}
# Location: GitHub # Website: https://github.com/biosurf/cyCombine
#cyCombine allows for robust integration of single-cell cytometry datasets within and across technologies
install_github("biosurf/cyCombine")
```

```{r}
#The CytoML package is a powerful R/Bioconductor package designed to enable cross-platform import, export, and sharing of gated cytometry data. It facilitates interoperability between the R computational environment and commercial software platforms like FlowJo, Cytobank, and Diva
# Location: Bioconductor
# Website: https://www.bioconductor.org/packages/release/bioc/html/CytoML.html

install.packages("CytoML")
```

```{r}
# Location: CRAN
# Website: https://github.com/jkrijthe/Rtsne
#Dimensionality Reduction: It reduces complex, high-dimensional data into a lower-dimensional representation while preserving local relationships and patterns.Visualization: It is particularly effective for visualizing data clusters that cannot be separated by linear methods like Principal Component Analysis (PCA).
install.packages("Rtsne")
```

```{r}
# Location: CRAN
# Website:https://jlmelville.github.io/uwot/
#package is an R implementation of the Uniform Manifold Approximation and Projection (UMAP) algorithm for dimensionality reduction. It allows users to reduce high-dimensional data into a lower-dimensional space (e.g., a 2D or 3D plot) while preserving the underlying data structure
install.packages("uwot")
```